FROM ubuntu:20.04

#ARG CUDA_KEYRING_URL=https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb

ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /setup

RUN \
	apt update && \
	apt install -y \
		python3.9 \
		python3.9-dev \
		python3.9-venv \
		doxygen \
		cmake \
		&& \
	:

COPY ./requirements-dev.txt ./requirements-dev.txt
RUN \
	python3.9 -m venv /venv && \
	. /venv/bin/activate && \
	pip install -r requirements-dev.txt && \
	:

WORKDIR /app


